# Serverless Config

service: erebus
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  timeout: 60  # optional, in seconds, default is 6

functions:
  loadtest :
    handler: handler.loadtest
    # provisionedConcurrency: 1 
    # reservedConcurrency: 1
    events:
      - schedule: rate(1 minute)

